### ISSUE TITLE
Error when I use demo.py to visulize result. How can I add images as input?

### ISSUE THREAD

**Issue by ChunZheng2022** [dvlab-research/FocalsConv#23]
2022-11-04 15:19:40,312   INFO  ==> Loading parameters from checkpoint ../output/kitti_models/fspconv80.pth to CPU
2022-11-04 15:19:40,362   INFO  ==> Checkpoint trained from version: pcdet+0.6.0+0000000
2022-11-04 15:19:40,411   INFO  ==> Done (loaded 653/653)
2022-11-04 15:19:40,586   INFO  Visualized sample index:        1
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 98, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/lcz/code/platform/openpcdet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/lcz/anaconda3/envs/cu113/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lcz/code/platform/openpcdet/pcdet/models/backbones_3d/spconv_backbone_focal.py", line 236, in forward
    x_image = self.semseg(batch_dict['images'])['layer1_feat2d']
KeyError: 'images'

**Comment by yukang2017** [comment]
Hi, 

The demo function in OpenPCDet currently does no support reading images yet. For this issue you should post it in the official OpenPCDet repo.
