### ISSUE TITLE
KeyError: 'model_state'

### ISSUE THREAD

**Issue by guoziteng** [dvlab-research/FocalsConv#35]
![微信图片_20240514163113](https://github.com/dvlab-research/FocalsConv/assets/147492498/7ed4cd00-d71f-40a5-9273-a1d59d6fa6cc)

**Comment by C-jacker** [comment]
I also met this issue. Have you solved this problem？

**Comment by C-jacker** [comment]
2024-11-06 17:19:35,343   INFO  ==> Loading parameters from checkpoint ../checkpoints/deeplabv3_resnet50_coco-cd0a2569.pth to GPU
Traceback (most recent call last):
  File "/tmp/OfficialOpenPCDet/tools/train.py", line 237, in <module>
    main()
  File "/tmp/OfficialOpenPCDet/tools/train.py", line 147, in main
    model.load_params_from_file(filename=args.pretrained_model, to_cpu=dist_train, logger=logger)
  File "/tmp/OfficialOpenPCDet/tools/../pcdet/models/detectors/detector3d_template.py", line 368, in load_params_from_file
    model_state_disk = checkpoint['model_state']
KeyError: 'model_state'
